### ISSUE TITLE
v1.0.4: Calendar doesn't respect "read-only" mode

### ISSUE THREAD

**Issue by chrispenny** [praxisnetau/silverware-calendar#1]
Firstly - awesome module!

The only issue I've found is that the calendar appears to still be accessible when `DateField`/`DatetimeField`/etc are read only. The form below is on a Page with `canEdit()` set to `false`:
![screen shot 2017-11-28 at 12 37 03 pm](https://user-images.githubusercontent.com/505788/33336824-0b1f7e90-d4d6-11e7-9faf-3eaa68c4877e.png)

I would be more than happy to submit a Pull Request for this, but wanted to check where you would like this logic to live?

I thought perhaps putting an extra check under `FormFieldExtension::getCalendarEnabled()` would be ok, but please let me know.

**Comment by colintucker** [comment]
Hi @chrispenny - thanks for reporting this! I've just pushed a commit to `dev-master` that should fix this (the test is in `getCalendarEnabled()` as you mentioned), are you able to verify for me that it's fixed for you?

**Comment by chrispenny** [comment]
Perfect! Thank you very much for doing that so quickly, @colintucker .
