### ISSUE TITLE
24 hours format on field

### ISSUE THREAD

**Issue by pmacinec** [praxisnetau/silverware-calendar#3]
Hello. 

I have a problem with 24 hours format on Datetimefield.

There is my code:
```php
$field = DatetimeField::create('MyDatetime', 'MyDatetime');
$field->setCalendarConfig([
    'time_24hr' => true,
    'dateFormat' => 'd. m. Y H:mm'
]);
```
Problem is, that even when timepicker has 24 hours format, SS field after choosing time is displaying date and time still in 12 hours format.

![field](https://user-images.githubusercontent.com/22483624/44470648-9137f180-a62a-11e8-909e-1c57fde81a89.png)

Am I doing anything bad, or it is not supported?

Thanks.

**Comment by brasileric** [comment]
I experience the same issue. Have you already found a solution?

**Comment by pmacinec** [comment]
No, still same problem :(

**Comment by colintucker** [comment]
Hi @brasileric and @pmacinec - thanks for reporting this issue, I will have a look into it and see if I can figure out what is going wrong.

**Comment by Chaofaa** [comment]
```
$field = DatetimeField::create('MyDatetime', 'MyDatetime');
$field->setCalendarConfig([
    'altInput' => false, // This append AM/PM
    'allowInput' => true // Allow edit
    'time_24hr' => true,
    'dateFormat' => 'd. m. Y H:mm'
]);
```

**Comment by pmacinec** [comment]
Thanks @Chaofaa, this is what I have been looking for! Working as expected.

*Note: For other users, be careful, `'dateFormat' = 'd. m. Y H:mm'` is not completely correct, you should use `i` for minutes instead of `mm`. Even after that, SilverStripe will not work correctly and will save another datetime, because calendar will show correct date, but SS will expect year to be first, so you have to format it by yourself.*
